## Numpy

https://numpy.org/devdocs/user/absolute_beginners.html

In [ ]:
import numpy as np
import pandas as pd


https://numpy.org/learn/

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

a.shape # (rows,columns) qator va ustunlar soni
np.shape(a)

np.ndim(a) # 2d arrayning o'lchami

np.size(a) # elementlar soni

6

**Arrayni Yaratish usullari**

In [ ]:
np.zeros((2,4)) # barcha elementlari 0 ga teng bo'lgan shape(2,4) 2darray

np.ones((2,4)) # barcha elementlari 1 ga teng bo'lgan shape(2,4) 2darray

np.arange(4,20,2).reshape(2,4) # 4 bilan boshlanib 20 gacha bo'lgan qadamlari 2 teng 2d array

c = np.random.rand(2,4) # o'lchami(2,4) teng . (0-1) oralig'idagi o'nlik sonlar

np.random.randn(2,4) # o'lchami(2,4) teng . (+,-) o'nlik sonlar

np.random.randint(5,size=(2,4)) # max 5 bo'lgan butun sonlar

np.linspace(0, 10, num=5) # 0 dan 10 gacha 5 qismga ajratilgan

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
a.dtype # malumot turini aniqlash
a.astype(np.float64) # malumot turini o'zgartirish

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
b=np.arange(10)

b[3:5] # index 0 dan boshlanadi . 3 dan 5 gacha kesish , 5 kirmaydi.

b[:] # to'liq nusxa olish

a[:1,1:] # [qator,ustun] 2d arrayda kesish


array([[2, 3]])

In [ ]:
A = np.arange(6).reshape(2,3)
A #(2,3)
A.T # (3,2) -- > A.swapaxes(1,0)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
np.sqrt(A) # array barcha elementlarini kv ildizini hisoblaydi
np.square(A) # array barcha elementlarini kvadratini hisoblaydi

q,b = np.modf(c) # qoldiq va butun qili aloxida arrayga saqlaydi

np.sign(A) # manfiy elementlar (-1) musbat elementlar (+1) qilib saqlaydi

np.isnan(A) # NaN qiymatlar(True), yo'q bo'lsa (False)

array([[False, False, False],
       [False, False, False]])

In [ ]:
np.add(A,a) # A + A.T
np.subtract(A,a) # A - A.T

np.min(A) # minimum qiymatlarni qaytaradi
np.max(A) # maxsimum qiymatlarni qaytaradi

np.sum(A) # yig'indini hisoblaydi
np.mean(A) # o'rtacha qiymatni hisoblaydi

np.sort(A) # tartiblash kichikdan kattaga
-np.sort(-A) # teskari tartiblash kattadan kichikga
A[::-1] # teskari tartiblash kattadan kichikga

array([[3, 4, 5],
       [0, 1, 2]])

In [ ]:
np.unique(a) # takrorlanmas qiymatlarni qaytaradi

np.in1d(A,a) # A ning elementlarini a da borligini tekshiradi

np.setdiff1d(A,a) # A ning a daga takrorlanmas qiymatlarini qaytaradi

np.nonzero(A) # 0 ga teng bo'lmagan index elementlarini qaytaradi

(array([0, 0, 1, 1, 1]), array([1, 2, 0, 1, 2]))

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b)) # 2 ta arrayni birlashtirish

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0) # ustun bo'yicha birlashtirish

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

five_up = (a > 5) | (a == 5)
print(five_up)

c = a[(a > 2) & (a < 11)]
print(c)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 3  4  5  6  7  8  9 10]


In [ ]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

np.vstack((a1, a2))
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

reversed_arr = np.flip(arr) # teskariga aylantiradi

arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

x.flatten() # --> 1D array
a2 = x.ravel() # --> 1D array

NumPy - Statistical Functions

NumPy - Sort, Search & Counting Functions

https://www.tutorialspoint.com/numpy/numpy_sort_search_counting_functions.htm